typography_spectrum: 0.5913021632004529
color:
  brandStrength: 0.06688173720613122
  lightness: 0.9959703364875168
  saturation: 0.11266762809827924
  rhythmicContrast: 0.4551870012655854
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.17468530707992613
name: blog
navigation:
  - name: HOME
    url: 'http://www.taessina.com'
    type: external
title: Tsnx | Taes'Life
content: []
description: eat . basketball . code
purpose:
  - type: contact
    url: 'mailto:lawrence.cheng@taessina.com'
    label: Apply Internship
  - type: contact
    url: 'mailto:ken.low@taessina.com'
    label: Request Quotation
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2906be5a-511c-4f60-8707-b1d8efdb04ec.png
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4ea68b5-26da-4d61-be5d-7ddadc031288.png
