layout_spectrum: 0.3542824600592698
typography_spectrum: 0.5936616463647546
color:
  brandStrength: 0.22958878789696438
  lightness: 0.9958847508568427
  saturation: 0.37415017749966667
  rhythmicContrast: 0.050712945257396544
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7f635751-a8a1-402d-865f-3e05d8b308d5.png
name: blog
navigation:
  - name: HOME
    url: 'http://www.taessina.com'
    type: external
  - name: OUR STORY
    id: 6d1c019c-ce80-4859-9860-0ec505d62856
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4ea68b5-26da-4d61-be5d-7ddadc031288.png
title: Tsnx | Taes'Life
content: []
description: eat . basketball . code
purpose:
  - type: contact
    url: 'mailto:lawrence.cheng@taessina.com'
    label: Apply Internship
  - type: contact
    url: 'mailto:ken.low@taessina.com'
    label: Request Quotation
