layout_spectrum: 0.35113606636209577
typography_spectrum: 0.5978771611292948
color:
  brandStrength: 0.22733126930680383
  lightness: 0.997800827985445
  saturation: 0.37058429252752795
  rhythmicContrast: 0.015057891093120716
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
github: true
analytics:
  google: UA-85675342-2
author:
  name: written and maintained by tsnx
  email: taessina@gmail.com
  url: 'http://www.taessina.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7f635751-a8a1-402d-865f-3e05d8b308d5.png
name: Code with Taessina
navigation:
  - name: Reason to Hire Us
    id: 6d1c019c-ce80-4859-9860-0ec505d62856
    type: content
  - name: Being Tsnx
    id: 0be22171-fe61-4b09-8389-683857179a9e
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4ea68b5-26da-4d61-be5d-7ddadc031288.png
title: '"We code ''em all!" says Tsnx'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5341cde-8b10-4a0a-a00e-2a4f736e1bfe.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5341cde-8b10-4a0a-a00e-2a4f736e1bfe.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: eat . basketball . code
purpose:
  - type: contact
    url: 'mailto:ken.low@taessina.com'
    label: Request Quotation
url: 'http://www.taessina.com/'
