typography_spectrum: 0.5913021632004529
color:
  brandStrength: 0.06688173720613122
  lightness: 0.9959703364875168
  saturation: 0.11266762809827924
  rhythmicContrast: 0.4551870012655854
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
layout_spectrum: 0.17468530707992613
author:
  name: Then Yao Bin
  email: alvin.then@taessina.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7579db15-3f9c-4a27-ba1a-78a2ee0a9f27.svg
name: TSN Blog
navigation:
  - name: HOME
    url: 'http://www.taessina.com'
    type: external
title: My Tech Diary
content: []
description: brought to you by ythen
purpose: []
