typography_spectrum: 0.5913021632004529
color:
  brandStrength: 0.06688173720613122
  lightness: 0.9959703364875168
  saturation: 0.11266762809827924
  rhythmicContrast: 0.4551870012655854
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
layout_spectrum: 0.17468530707992613
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7f635751-a8a1-402d-865f-3e05d8b308d5.png
name: blog
navigation:
  - name: HOME
    url: 'http://www.taessina.com'
    type: external
  - name: OUR STORY
    id: 6d1c019c-ce80-4859-9860-0ec505d62856
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4ea68b5-26da-4d61-be5d-7ddadc031288.png
title: Tsnx | Taes'Life
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/47db5219-e270-4169-adcf-2ae9360f8a8a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/47db5219-e270-4169-adcf-2ae9360f8a8a.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: eat . basketball . code
purpose:
  - type: contact
    url: 'mailto:lawrence.cheng@taessina.com'
    label: Apply Internship
  - type: contact
    url: 'mailto:ken.low@taessina.com'
    label: Request Quotation
