layout_spectrum: 0.3542824600592698
typography_spectrum: 0.5936616463647546
color:
  brandStrength: 0.22958878789696438
  lightness: 0.9958847508568427
  saturation: 0.37415017749966667
  rhythmicContrast: 0.050712945257396544
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7f635751-a8a1-402d-865f-3e05d8b308d5.png
name: blog
navigation:
  - name: OUR STORY
    id: 6d1c019c-ce80-4859-9860-0ec505d62856
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4ea68b5-26da-4d61-be5d-7ddadc031288.png
title: Taes'Life @ Tsn
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5341cde-8b10-4a0a-a00e-2a4f736e1bfe.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5341cde-8b10-4a0a-a00e-2a4f736e1bfe.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: eat . basketball . code
purpose:
  - type: contact
    url: 'mailto:lawrence.cheng@taessina.com'
    label: Apply Internship
  - type: contact
    url: 'mailto:ken.low@taessina.com'
    label: Request Quotation
author:
  name: written and maintained by tsnx
  email: taessina@gmail.com
  url: 'http://www.taessina.com'
analytics:
  google: UA-85675342-2
